= Requisitos do jMonkeyEngine3
:author:
:revnumber:
:revdate: 2016/03/17 20:48
:relfileprefix: ../
:imagesdir: ..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


Esta página mostra os requisitos de software e hardware de duas perspetivas diferentes:

*  Para os desenvolvedores Java que criam jogos; e
*  Para os utilizadores (os seus clientes) que jogam os seus jogos.


== Para Desenvolvedores

Estes são os requisitos mínimos para desenvolvedores que cria jogos usando o jMonkeyEngine SDK:
[cols="30,70", options="header"]
|===

a|Sistema Operativo
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux, Solaris

a|Memória (tamanho do heap do JVM)
a| &gt; 40 +++<abbr title="Megabyte">MB</abbr>+++ ++ memória para os assets

a|CPU
a|&gt; 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|Placa gráfica
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, ou superior +
suporte a OpenGL 2.0 ou superior (as livrarias nativas estão incluídas com o download)

a|Java Development Kit
a|JDK 7 ou maior +
A sua equipa de desenvolvimento obtém o Java Development Kit gratuitamente daqui: link:http://www.java.com[http://www.java.com]; para Mac +++<abbr title="Operating System">OS</abbr>+++, ver link:http://support.apple.com/kb/DL1421[apple.com]. +
Um nível intermédio de experiência com Java é necessário

|===

Recomendamos o uso do <<sdk#,jMonkeyEngine SDK>> como a ferramenta de desenvolvimento do jogo (IDE). No entanto, qualquer outro IDE Java (e até um editor de texto e um terminal) pode ser usado e funciona bem com a framework jME, caso já tenha experiência em usar essa ferramenta. Para os requisitos de outros IDEs, consulte a documentação de terceiros.


== Para Utilizadores

Estes são os requisitos mínimos para os seus clientes, os utilizadores que jogam jogos criados com o jMonkeyEngine3:
[cols="30,70", options="header"]
|===

a|Sistema Operativo
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux, Solaris

a|Memória (tamanho do heap do JVM)
a| &gt; 10 +++<abbr title="Megabyte">MB</abbr>+++ ++ memória paraos assets (modelos, texturas, sons, etc, dum jogo em particular)

a|CPU
a|&gt; 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|Placa gráfica
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, ou superior +
suporte a OpenGL 2.0 ou superior (as livrarias nativas estão incluídas com o download)

a|link:https://hub.jmonkeyengine.org/t/does-my-phone-meet-the-requirements-necessary-to-run-jmonkeyengine-3/17231[Dispositivos Android]
a|(Apenas para jogos móveis) Android 2.2 +++<abbr title="Operating System">OS</abbr>+++, placa gráfica que suporte OpenGL 2

a|Java Runtime
a|Java 5 ou maior +
O Java Virtual Machine (JVM) é necessário para correr jogos jME. +
Geralmente o JVM já vem pré-instalado, caso não tenham, os seus utilizadores podem obtê-lo aqui: link:http://www.java.com[http://www.java.com]; para Mac +++<abbr title="Operating System">OS</abbr>+++, ver link:http://support.apple.com/kb/DL1421[apple.com].

|===

Certifique-se de que informa os seus utilizadores quanto aos requisitos.
Make sure to inform your users about these requirements.
