= "Qual devo escolher? jME2 ou jME3?"
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:keywords: about
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


Como esta é uma das perguntas mais frequentes no jME, está página tem o objetivo de a responder plenamente. Para obter mais informação sobre as funcionalidades, por favor consulte esta <<compare-jme2-jme3#, comparação entre jME2 e jME3>>.

Se ainda não tem a certeza da sua escolha, ficaremos felizes em responder às suas perguntas no fórum. Muitas delas, no entanto, já foram respondidas, então por favor comece por procurar alguns termos como 'jme2 and jme3' e pode ser que encontre a sua dúvida já respondida.


== Porquê escolher jME3?


=== Gráficos da atual & próxima geração

Desde o início que o jME3 foi construído a pensar nos príncipios e hardware moderno. Ao ser baseado em shaders e suportando apenas OpenGL2 ou maior, o jME3 destina-se aos computadores modernos de hoje, e dos que estarão por vir. Suporte a OpenGL 1 está limitado apenas às bases de mostrar modelos com texturas.


=== Desenvolvido ativamente

Ao contrário da sua versão anterior, o jME3 é desenvolvido muito ativamente por uma equipa de desenvolvedores principais e por uma comunidade enorme de contribuidores. Qualquer aspeto do jME3 pode ser discutido em qualquer altura.
P.S. Quanto mais cedo se envolver maiores são as probabilidades de causar um grande impacto no projeto.


=== Documentação sempre a melhorar

A maior parte da documentação feita hoje é feita para o jMonkeyEngine3. Embora naturalmente grande parte tenha sido um esforço pera comunidade, esta documentação beneficia muito mais de suporte e de iterações contínuas por parte da equipa principal.


=== jMonkeyEngine SDK

Com a <<sdk#,SDK>> do jMonkeyEngine, o jME3 é a primeira versão do jME com uma IDE decidada para desenvolvimento e distrubuição de aplicações, gestão de assets e ferramentas de composição.


=== Vasto leque de funções

Um grande objetivo para o jME3 é "não deixar nada essencial de game-dev para trás". Temos como objetivo fornecer, "straight out of the box", todos os básicos necessários para desenvolver protótipos para praticamente qualquer tipo de jogo: física, networking, terreno e muito mais, tudo junto, mas nunca forçando. Pode sempre substituir qualquer funcionalidade que não corresponda ao seu jogo com uma solução personalizada feita por si.


=== Ficamos muito felizes de o ter!

Naturalmente que ficamos excitados sempre que alguém decida adotar o jME3 para desenvolver [jogos]. Objetivamente falando, isso significa mais testes, mais commits, mais ação, mais projetos, mais inovação; uma comunidade melhor.


== Porquê escolher jME2?


=== Estável até hoje

O jME2 encontra-se estável desde 2009, sem nenhuma grande funcionalidade adicionada ou modificada desde 2008. Embora haja planos para uma versão final (2.1), o jME2 está praticamente em completo "feature freeze".


=== Suporte para computadores low-end

O jME2 suporta totalmente o OpenGL 1, enquanto que o jME3 não. Se juntar alguma programação cuidada, consegue obter requisitos de hardware muito baixos para os seus projetos.


=== Ferramentas da comunidade

Existem ferramentas muito bem escritas como o SceneMonitor e o SceneWorker que enriquecem muito o uso da engine.


=== Documentada detalhadamente

Existem literalmente centenas de páginas de documentação para o jMonkeyEngine 2.0, detalhados práticas de desenvolvimento com a engine desde níveis principiantes até intermédios e avançados. Note, no entanto, que ao dar-se o crescimento do jME3, esta documentação será mantida apenas pela comunidade (veja a secção 'Documentação sempre a melhorar' na secção do jME3 acima).
