= Documentação do jMonkeyEngine
:author:
:revnumber:
:revdate: 2016/03/17 20:48
:experimental:
:keywords: documentation, sdk, install
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


Esta wiki de documentação contém guias de instalação e configuração, tutoriais de jME e outras informações que o irão ajudar no seu projeto de jogo. Pode procurar pelos conteúdos desta wiki usando a barra de pesquisa no topo da página.

Também é muito bem-vindo a reparar quaisquer erros tanto de informação como de escrita, assim como parágrafos vagos, usando o menu "`Wiki`" no topo ou os botões de "`Edit`" ao pé de cada parágrafo. Tem de ter sessão iniciada para poder editar esta wiki.

TIP: Isto é um Balão. Irá encontrar muitos destes espalhados pela Wiki, Veja os <<wiki/admonitions#,Significados dos Balões>> para saber o significado deste e de todos os outros Balões.

== Instalar

*Antes de instalar, veja a <<bsd_license#,licença>>, <<jme3/features#,funcionalidades>>, e os <<jme3/requirements#,requisitos>>.* Depois escolha uma destas opções:
[cols="4", options="header"]
|===

a|
<a| Recomendado
<a| Opcional
<a| Opcional

a| Você quer…
a| Começar a usar jMonkeyEngine
a| Usar jMonkeyEngine noutra IDE
a| Criar uma engine personalizada com o código-fonte

a| Então descarregue…
a| link:https://github.com/jMonkeyEngine/sdk/releases[jMonkeyEngine SDK]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine/releases[Binários]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine[Código fonte da Engine]

a| Irá obter…
a| SDK, binários, javadoc, código fonte
a| Binários, javadoc, código fonte
a| Código fonte

a| Aprenda mais aqui…
a|
* <<sdk#,Como usar o SDK>>
* <<sdk/project_creation#,Criação de Projetos>>
a|
* <<jme3/maven#,Configurar o jME3 com IDEs compatíveis com maven>>
* <<jme3/setting_up_netbeans_and_jme3#,Configurar o jME3 na IDE NetBeans >>
* <<jme3/setting_up_jme3_in_eclipse#,Configurar o jME3 na IDE Eclipse>>
* <<jme3/eclipse_jme3_android_jnindk#,Configurar o jME3 na IDE Eclipse (com Android e/ou JNI/NDK)>>
a|
* <<jme3/build_from_sources#,Compilar o JME3 a partir do código-fonte>>
* <<jme3/build_jme3_sources_with_netbeans#,Compilar o JME3 a partir do código-fonte com o NetBeans>>
* <<jme3/simpleapplication_from_the_commandline#,Configurando o JME3 na linha de comandos>>
|===

pass:[*] O SDK cria projetos baseados em Ant que qualquer IDE de Java pode importar. Recomendamos aos utilizadores doutras IDEs para tabém descarregarem o jMonkeyEngine SDK e escolherem `menu:File[Import Project > External Project Assets]` para criar um projeto sem código para gerir só os assets. Desta forma pode programar em qualquer IDE à sua escolha, e usar o SDK para converter os seus modelos para o formato .j3o.


== Criar

Depois de descarregar e instalar, <<jme3#,guarde a página de documentação do jME nos favoritos>> e comece a escrever o seu primeiro jogo!
[cols="3", options="header"]
|===

a| Tutoriais
a| jMonkeyEngine SDK
a| Outra documentação

a| <<jme3#tutorials-for-beginners,Tutoriais principiantes de jME3>>
a| <<sdk#,Documentação do jMonkeyEngine SDK e Tutoriais de Vídeo>>
a| link:http://javadoc.jmonkeyengine.org/[JavaDoc da API completa]

a| <<jme3#documentation-for-intermediate-users,Artigos intermédios do jME3>>
a| <<sdk/comic#,jMonkeyEngine SDK - a Banda Desenhada :-)>>
a| <<jme3/external/blender#,Guia de Modelação para Blender>>

a| <<jme3#documentation-for-advanced-users,Documentação avançada do jME3>>
<a|
a| <<jme3/faq#,Respostas a Perguntas Frequentes>>

|===


== Contribuir

É um desenvolvedor experiente de Java que quer adicionar novas funcionalidades ou contribuir com patches para o projeto jME3?

*  Inspire-se com as <<jme3/contributions#,contribuições>> já existentes
*  link:https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/CONTRIBUTING.md[Como contribuir para o jMonkeyEngine]
*  link:https://github.com/ev1lbl0w/jme-wiki-pt-pt[Torne-se um Editor da Wiki]
*  link:http://hub.jmonkeyengine.org/c/contribution-depot-jme3[Junte-se ao Fórum de Contribuidores]
*  <<jme3/jme3_source_structure#,Aprenda a estrutura do código-fonte>>
*  <<sdk#development,Escrever plugins para o jMonkeyEngine SDK e editores visuais>>
*  <<report_bugs#,Reportar bugs e submeter patches>>


== Contactar

É bem-vindo a contribuir e a questionar sobre o projeto: Por favor contacte os link:https://hub.jmonkeyengine.org/badges/103/core-developer[desenvolvedores] ou pergunte nos link:http://hub.jmonkeyengine.org/[fóruns].

*  link:https://hub.jmonkeyengine.org/badges/103/core-developer[Contacte a equipa do jME]
**  <<team#,[Equipa principal - Quem somos?]>>

*  <<report_bugs#,Reportar um bug>>
*  link:http://hub.jmonkeyengine.org/c/documentation-jme3[Reportar documentação vaga ou em falta]


== Línguas

A equipa está à procura doutros "monkeys" que estejam interessados em traduzir a wiki para [inserir língua favorita aqui]. Caso esteja interessado em hospedar traduções veja a página <<wiki\wiki_translation.adoc#,Repositórios de Tradução da Wiki>>.

<<documentacao#,Documentação em Português>> +
link:http://www.jmecn.net/wiki/[简体中文]
